type VenueLayout @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  elements: String! # JSON string of CanvasElements
  createdAt: Timestamp! @default(expr: "request.time")
}

type Event @table {
  id: UUID! @default(expr: "uuidV4()")
  title: String!
  venueName: String!
  venueLat: Float!
  venueLng: Float!
  description: String
  startTime: Timestamp! @default(expr: "request.time")
  expiryDate: Timestamp
  bannerUrl: String
  isActive: Boolean! @default(value: false)
  minAge: Int @default(value: 0)
  layoutId: UUID
  layoutConfig: String # JSON mapping element ID -> capacity configuration
}

type Ticket @table {
  id: UUID! @default(expr: "uuidV4()")
  issuedAt: Timestamp! @default(expr: "request.time")
  gate: String!
  section: String!
  row: String!
  seat: String!
  status: String! @default(value: "ACTIVE")
  
  # Guest Information
  guestName: String!
  guestAge: Int!
  guestIdNumber: String!
  guestMobile: String!
  guestEmail: String!
  
  # Relationships
  eventId: UUID!
}

type EmergencyEvent @table {
  id: UUID! @default(expr: "uuidV4()")
  eventId: UUID # Optional link to an active event
  type: String!
  priority: String!
  details: String!
  lat: Float
  lng: Float
  timestamp: Timestamp! @default(expr: "request.time")
  status: String! @default(value: "PENDING")
}

